// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: internal/ping/domain/ping.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PingMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PingMetaRequest) Reset() {
	*x = PingMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ping_domain_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMetaRequest) ProtoMessage() {}

func (x *PingMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ping_domain_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMetaRequest.ProtoReflect.Descriptor instead.
func (*PingMetaRequest) Descriptor() ([]byte, []int) {
	return file_internal_ping_domain_ping_proto_rawDescGZIP(), []int{0}
}

func (x *PingMetaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PingMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PingMetaResponse) Reset() {
	*x = PingMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ping_domain_ping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMetaResponse) ProtoMessage() {}

func (x *PingMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ping_domain_ping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMetaResponse.ProtoReflect.Descriptor instead.
func (*PingMetaResponse) Descriptor() ([]byte, []int) {
	return file_internal_ping_domain_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingMetaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PongMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PongMetaRequest) Reset() {
	*x = PongMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ping_domain_ping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMetaRequest) ProtoMessage() {}

func (x *PongMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ping_domain_ping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMetaRequest.ProtoReflect.Descriptor instead.
func (*PongMetaRequest) Descriptor() ([]byte, []int) {
	return file_internal_ping_domain_ping_proto_rawDescGZIP(), []int{2}
}

func (x *PongMetaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PongMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PongMetaResponse) Reset() {
	*x = PongMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ping_domain_ping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMetaResponse) ProtoMessage() {}

func (x *PongMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ping_domain_ping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMetaResponse.ProtoReflect.Descriptor instead.
func (*PongMetaResponse) Descriptor() ([]byte, []int) {
	return file_internal_ping_domain_ping_proto_rawDescGZIP(), []int{3}
}

func (x *PongMetaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_ping_domain_ping_proto protoreflect.FileDescriptor

var file_internal_ping_domain_ping_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x21, 0x0a, 0x0f, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x50, 0x69, 0x6e,
	0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x21, 0x0a,
	0x0f, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x22, 0x0a, 0x10, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x32, 0x78, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x35, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f, 0x6e, 0x67,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a,
	0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_ping_domain_ping_proto_rawDescOnce sync.Once
	file_internal_ping_domain_ping_proto_rawDescData = file_internal_ping_domain_ping_proto_rawDesc
)

func file_internal_ping_domain_ping_proto_rawDescGZIP() []byte {
	file_internal_ping_domain_ping_proto_rawDescOnce.Do(func() {
		file_internal_ping_domain_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ping_domain_ping_proto_rawDescData)
	})
	return file_internal_ping_domain_ping_proto_rawDescData
}

var file_internal_ping_domain_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_ping_domain_ping_proto_goTypes = []interface{}{
	(*PingMetaRequest)(nil),  // 0: rpc.PingMetaRequest
	(*PingMetaResponse)(nil), // 1: rpc.PingMetaResponse
	(*PongMetaRequest)(nil),  // 2: rpc.PongMetaRequest
	(*PongMetaResponse)(nil), // 3: rpc.PongMetaResponse
}
var file_internal_ping_domain_ping_proto_depIdxs = []int32{
	0, // 0: rpc.Metadata.Ping:input_type -> rpc.PingMetaRequest
	2, // 1: rpc.Metadata.Pong:input_type -> rpc.PongMetaRequest
	1, // 2: rpc.Metadata.Ping:output_type -> rpc.PingMetaResponse
	3, // 3: rpc.Metadata.Pong:output_type -> rpc.PongMetaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_ping_domain_ping_proto_init() }
func file_internal_ping_domain_ping_proto_init() {
	if File_internal_ping_domain_ping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ping_domain_ping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ping_domain_ping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ping_domain_ping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ping_domain_ping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ping_domain_ping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ping_domain_ping_proto_goTypes,
		DependencyIndexes: file_internal_ping_domain_ping_proto_depIdxs,
		MessageInfos:      file_internal_ping_domain_ping_proto_msgTypes,
	}.Build()
	File_internal_ping_domain_ping_proto = out.File
	file_internal_ping_domain_ping_proto_rawDesc = nil
	file_internal_ping_domain_ping_proto_goTypes = nil
	file_internal_ping_domain_ping_proto_depIdxs = nil
}
