sequenceDiagram
    autonumber
    participant p0 as microservice-template-ddd.api
    actor p1 as client
    participant p2 as microservice-template-ddd.billing
    p1->>p0: GET /billing/
    p0->>p2: Get
    p2->>p2: Get
    p2-->>p0: GetResponse
    alt err != nil
        rect rgba(183, 100, 107, 0.12)
            p0-->>p1: 200 · Error
        end
        Note over p1: flow ends here
    else otherwise
    end
    alt err != nil
        rect rgba(183, 100, 107, 0.12)
            p0-->>p1: 200 · Error
        end
    else otherwise
    end
    p0-->>p1: 200 · GetResponse
