// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package billing_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BillingRPCClient is the client API for BillingRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingRPCClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type billingRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingRPCClient(cc grpc.ClientConnInterface) BillingRPCClient {
	return &billingRPCClient{cc}
}

func (c *billingRPCClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/billing.BillingRPC/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingRPCServer is the server API for BillingRPC service.
// All implementations must embed UnimplementedBillingRPCServer
// for forward compatibility
type BillingRPCServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedBillingRPCServer()
}

// UnimplementedBillingRPCServer must be embedded to have forward compatible implementations.
type UnimplementedBillingRPCServer struct {
}

func (UnimplementedBillingRPCServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBillingRPCServer) mustEmbedUnimplementedBillingRPCServer() {}

// UnsafeBillingRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingRPCServer will
// result in compilation errors.
type UnsafeBillingRPCServer interface {
	mustEmbedUnimplementedBillingRPCServer()
}

func RegisterBillingRPCServer(s *grpc.Server, srv BillingRPCServer) {
	s.RegisterService(&_BillingRPC_serviceDesc, srv)
}

func _BillingRPC_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingRPCServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingRPC/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingRPCServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BillingRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingRPC",
	HandlerType: (*BillingRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BillingRPC_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/billing/infrastructure/rpc/billing_rpc.proto",
}
